### ISSUE TITLE
Required VS created data files

### ISSUE THREAD

**Issue by cgerlein** [vuolleko/dew_collection#1]
Hi, 

I have been trying to get the code package running to produce regional versions of the global maps presented in the paper associated with the code. However, I have been having some troubles understanding which data files I had to provides and which ones were produced by the package itself. All I have is the ERA-Interim dataset including all 7 variables required in the paper and the README file. However, the plot_dewpot.py requires a file that I don't believe gets created by the code package:
`filename = 'data/dewpot/dew' + emissivity + 'ri_ysm.nc'`
I am not too familiar with cython, so I might have missed it? 

I am also a bit confused as to what can be run independently, and what can't. Ideally, I would like to test out the code on a year long dataset (for example) before running it on the entire dataset. 
So far, I've only been able to run the example_2days.py.

Thank you in advance for your help!

Cynthia

**Comment by vuolleko** [comment]
Hi Cynthia,

Nice to hear that you show interest in my work. My apologies, the
documentation could indeed be improved.

The plotting script plot_dewpot.py is a post-processing script, which plots
summary data that I created with the CDO tool. So you would have to run the
model first to generate the data. To run the model, you have to call the
method dew_interface.get_dew as in example_2days.py and daily_dew_jug.py.

If you only want the summary data with parameters already presented in the
paper, I can also send you the post-processed summary data (altogether
around 1 GB). Unfortunately I no longer have the raw model output, as that
was several 100 GB.

You can mail me directly at henri.vuollekoski at helsinki.fi.
- Henri
